
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 579;
const int acc_off_y = -167;
const int acc_off_z = -405;
const float acc_scale_x = 16217.440036;
const float acc_scale_y = 16373.871816;
const float acc_scale_z = 16594.512586;

const int magn_off_x = -109;
const int magn_off_y = -214;
const int magn_off_z = -33;
const float magn_scale_x = 562.712991;
const float magn_scale_y = 506.715086;
const float magn_scale_z = 398.882980;
