
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 548;
const int acc_off_y = -177;
const int acc_off_z = -430;
const float acc_scale_x = 16133.396645;
const float acc_scale_y = 16338.137220;
const float acc_scale_z = 16569.128840;

const int magn_off_x = -107;
const int magn_off_y = -218;
const int magn_off_z = -33;
const float magn_scale_x = 557.841785;
const float magn_scale_y = 510.287193;
const float magn_scale_z = 398.839283;
